sudo: required
services:
  - docker

before_install:
  - docker build -t melihx/docker-react -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true melihx/docker-react npm run test -- --coverage

after_success:
  - docker build -t melihx/multi-client ./client
  - docker build -t melihx/multi-nginx ./nginx
  - docker build -t melihx/multi-server ./server
  - docker build -t melihx/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push melihx/multi-client
  - docker push melihx/multi-nginx
  - docker push melihx/multi-server
  - docker push melihx/multi-worker


deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucker_name: "elasticbeanstalk-eu-central-1-514388363370"
  bucker_path: docker-multi
  on:
    branch: master

  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
